# Generated by Django 5.1.6 on 2025-02-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tanaman', models.CharField(max_length=100)),
                ('jenis_tanaman', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='biayaoperasional',
            name='siswa_petani',
        ),
        migrations.RemoveField(
            model_name='pendapatan',
            name='hasil_panen',
        ),
        migrations.RemoveField(
            model_name='pendapatan',
            name='siswa_petani',
        ),
        migrations.DeleteModel(
            name='StatistikPanen',
        ),
        migrations.RenameField(
            model_name='hasilpanen',
            old_name='jenis_tanaman',
            new_name='lokasi_lahan',
        ),
        migrations.RemoveField(
            model_name='hasilpanen',
            name='jumlah_kg',
        ),
        migrations.RemoveField(
            model_name='hasilpanen',
            name='lokasi',
        ),
        migrations.RemoveField(
            model_name='hasilpanen',
            name='musim',
        ),
        migrations.RemoveField(
            model_name='hasilpanen',
            name='siswa_petani',
        ),
        migrations.AddField(
            model_name='hasilpanen',
            name='jumlah_panen',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hasilpanen',
            name='tanaman',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='product_monitoring_app.tanaman'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BiayaOperasional',
        ),
        migrations.DeleteModel(
            name='Pendapatan',
        ),
    ]
