# Generated by Django 5.1.6 on 2025-02-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_monitoring_app', '0002_tanaman_remove_biayaoperasional_siswa_petani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilpanen',
            name='musim_tanam',
            field=models.CharField(choices=[('musim_hujan', 'Musim Hujan'), ('musim_kemarau', 'Musim Kemarau')], default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BiayaOperasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('pupuk', 'Pupuk'), ('pestisida', 'Pestisida'), ('tenaga_kerja', 'Tenaga Kerja'), ('lainnya', 'Lainnya')], max_length=50)),
                ('jumlah_biaya', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_pengeluaran', models.DateField()),
                ('tanaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_monitoring_app.tanaman')),
            ],
        ),
        migrations.CreateModel(
            name='Pendapatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pendapatan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hasil_panen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_monitoring_app.hasilpanen')),
            ],
        ),
    ]
