# Generated by Django 5.1.6 on 2025-02-18 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_monitoring_app', '0003_hasilpanen_musim_tanam_biayaoperasional_pendapatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biayaoperasional',
            name='tanaman',
        ),
        migrations.AddField(
            model_name='biayaoperasional',
            name='hasil_panen',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='product_monitoring_app.hasilpanen'),
            preserve_default=False,
        ),
    ]
